### ISSUE TITLE
JS & CSS route need to detect query string

### ISSUE THREAD

**Issue by ivankristianto** [wp-id/mcw-pwa#2]
In this line of code:
https://github.com/tyohan/mcw-pwa/blob/master/scripts/sw.js#L7

It doesn't detected css/js with query string for example:
jquery.js?ver=4.9.4

I did tweak the code and change it to:
```
workbox.routing.registerRoute(
    /\.(?:js|css)(.*)?$/,
    workbox.strategies.staleWhileRevalidate(),
  );
```

**Comment by tyohan** [comment]
This is one issue with WordPress that return the URL with versioning. I was remove this URL versioning in performance module which in performance branch, but not available yet in this Github repo. Will update it in next commit. Thanks

**Comment by ivankristianto** [comment]
in some cases it's good to have url versioning to bust the cache.
for example web behind cloudflare, we need to have script versioning to make sure our visitors get the latest script.

**Comment by tyohan** [comment]
Yes agree, is the versioning in WordPress based on WordPress version or the library version? I'm aware with cache busting, and Workbox has versioning parameter in their precache list and I'm thinking to use file hashing instead that version URL parameter. So it will be like this
```
workbox.precaching.precacheAndRoute(
  [
    { url: '/index.html', revision: '383676' },
    { url: '/scripts/jquery.js, revision: '383672' },
    { url: '/styles/main.css, revision: '3832322' },
  ]);
```

But WordPress using that URL versioning by default so better to keep it. My only concern is, the revision is related to WordPress versioning or the library versioning?

**Comment by ivankristianto** [comment]
By default all WordPress core js & css have WordPress version as the versioning parameter.
