### ISSUE TITLE
How to add new custom rules to service workers.

### ISSUE THREAD

**Issue by krloshc** [wp-id/mcw-pwa#9]
How to add new custom rules to service workers, without modifying the PLUGIN / scripts / sw.js

**Comment by tyohan** [comment]
@krloshc sorry for late response. We just got back from long travel for an event. We don't have a feature to do this for now. But seems like a good idea. What the best way to do this that you prefer? Do you prefer writing your own script, or better to have like UI admin panel to create a custom rule.
